export const SET_STATE = 'SET_STATE';
export const SET_OWNERS = 'SET_OWNERS';
export const SET_TO_ADD_INPUT = 'SET_TO_ADD_INPUT';
export const SET_OWNERS_TO_ADD = 'SET_OWNERS_TO_ADD';
export const REMOVE_OWNERS_FROM_TO_ADD = 'REMOVE_OWNERS_FROM_TO_ADD';
export const SELECT_OWNERS_FROM_TO_ADD = 'SELECT_OWNERS_FROM_TO_ADD';
export const SELECT_OWNERS_FROM_MAIN = 'SELECT_OWNERS_FROM_MAIN';
